## Add all Slack integration endpoints here
axonops_slack_integration:
- name: example_slack_integration_developer
  webhook_url: https://hooks.slack.com/services/ADD/ME/HERE
  channel: example_slack_integration_developer
- name: example_slack_integration_ops
  webhook_url: https://hooks.slack.com/services/ADD/ME/HERE
  channel: example_slack_integration_ops
- name: example_slack_integration_backups
  webhook_url: https://hooks.slack.com/services/ADD/ME/HERE
  channel: example_slack_integration_backups
- name: example_slack_integration_metrics
  webhook_url: https://hooks.slack.com/services/ADD/ME/HERE
  channel: example_slack_integration_metrics
- name: example_slack_integration_repair
  webhook_url: https://hooks.slack.com/services/ADD/ME/HERE
  channel: example_slack_integration_repair

## Add all Pagerduty integration endpoints here
axonops_pagerduty_integration:
- name: example_pagerduty_integration_developer
  integration_key: 123456789abc
- name: example_pagerduty_integration_ops
  integration_key: 123456789abc


## Add all Opsgenie integration endpoints here
axonops_opsgenie_integration:
- name: example_opsgenie_integration_developer
  opsgenie_key: https://api.opsgenie.com/v1/json/azureservicehealth?apiKey=aaabbbcccddd
- name: example_opsgenie_integration_ops
  opsgenie_key: https://api.opsgenie.com/v1/json/azureservicehealth?apiKey=aaabbbcccddd


## Add all ServiceNow integration endpoints here
axonops_servicenow_integration:
- name: example_servicenow_integration_developer
  instance_name: aaaabbbbccccdddd
  user: servicenowuserdev
  password: "I <3 AxonOps!"
- name: example_servicenow_integration_ops
  instance_name: eeeeffffgggghhhh
  user: servicenowuser
  password: "I <3 AxonOps!"

## Add all Microsoft Teams integration endpoints here
axonops_teams_integration:
- name: example_teams_integration_developer
  webhook_url: https://abcx360.webhook.office.com/aaabbbccc
- name: example_teams_integration_ops
  webhook_url: https://abcx360.webhook.office.com/aaabbbccc
