- hosts: localhost
  name: "Creates or Update the AxonOps service checks"
  become: false
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Get the Org name
      tags: always
      ansible.builtin.set_fact:
        org: "{{ lookup('env', 'AXONOPS_ORG') }}"
      when: org is not defined

    - name: Get the cluster name
      tags: always
      ansible.builtin.set_fact:
        cluster: "{{ lookup('env', 'AXONOPS_CLUSTER') }}"
      when: cluster is not defined

    - name: Fail if no org
      ansible.builtin.assert:
        that:
          - org is defined
          - org | length > 1
          - cluster is defined

    - name: Initialize axonops_shell_check
      tags: always
      ansible.builtin.set_fact:
        axonops_shell_check: "{{ axonops_shell_check | default([]) }}"

    - name: Load organization-wide shell check rules
      tags: always
      ansible.builtin.set_fact:
        axonops_shell_check: "{{ axonops_shell_check + (lookup('file', item) | from_yaml).axonops_shell_check }}"
      with_fileglob:
        - "config/{{ org }}/service_checks.yml"

    - name: Load cluster-specific shell check rules
      tags: always
      ansible.builtin.set_fact:
        axonops_shell_check: "{{ axonops_shell_check + (lookup('file', item) | from_yaml).axonops_shell_check }}"
      with_fileglob:
        - "config/{{ org }}/{{ cluster }}/service_checks.yml"

    - name: Initialize axonops_tcp_check
      tags: always
      ansible.builtin.set_fact:
        axonops_tcp_check: "{{ axonops_tcp_check | default([]) }}"

    - name: Load organization-wide tcp check rules
      tags: always
      ansible.builtin.set_fact:
        axonops_tcp_check: "{{ axonops_tcp_check + (lookup('file', item) | from_yaml).axonops_tcp_check }}"
      with_fileglob:
        - "config/{{ org }}/service_checks.yml"

    - name: Load cluster-specific tcp check rules
      tags: always
      ansible.builtin.set_fact:
        axonops_tcp_check: "{{ axonops_tcp_check + (lookup('file', item) | from_yaml).axonops_tcp_check }}"
      with_fileglob:
        - "config/{{ org }}/{{ cluster }}/service_checks.yml"

    - name: Apply TCP Check on {{ org }}/{{ cluster }}
      axonops.configuration.tcp_check:
        org: "{{ org }}"
        cluster: "{{ cluster }}"
        present: "{{ item.present|default(true) }}"
        name: "{{ item.name|default('') }}"
        interval: "{{ item.interval }}"
        timeout: "{{ item.timeout }}"
        tcp: "{{ item.tcp }}"
      with_items:
        "{{ axonops_tcp_check }}"
      tags:
      - axonops_tcp_check
      - tcp_check
      - check
      - tcp

    - name: Apply Shell Check on {{ org }}/{{ cluster }}
      axonops.configuration.shell_check:
        org: "{{ org }}"
        cluster: "{{ cluster }}"
        present: "{{ item.present|default(true) }}"
        name: "{{ item.name|default('') }}"
        interval: "{{ item.interval }}"
        timeout: "{{ item.timeout }}"
        shell: "{{ item.shell|default('/bin/bash') }}"
        script: "{{ item.script }}"
      with_items:
        "{{ axonops_shell_check }}"
      no_log: "{{ false if enable_logging is defined and enable_logging else true }}"
      tags:
      - axonops_shell_check
      - shell_check
      - check
      - shell

# code: language=ansible
