- hosts: localhost
  name: "Creates or Update the AxonOps log alerts"
  become: false
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Get the Org name
      tags: always
      ansible.builtin.set_fact:
        org: "{{ lookup('env', 'AXONOPS_ORG') }}"
      when: org is not defined

    - name: Get the cluster name
      tags: always
      ansible.builtin.set_fact:
        cluster: "{{ lookup('env', 'AXONOPS_CLUSTER') }}"
      when: cluster is not defined

    - name: Fail if no org
      ansible.builtin.assert:
        that:
          - org is defined
          - org | length > 1
          - cluster is defined

    - name: Initialize axonops_alert_rules
      tags: always
      ansible.builtin.set_fact:
        axonops_log_alert_rule: "{{ axonops_log_alert_rule | default([]) }}"

    - name: Load organization-wide alert rules
      tags: always
      ansible.builtin.set_fact:
        axonops_log_alert_rule: "{{ axonops_log_alert_rule + (lookup('file', item) | from_yaml).axonops_log_alert_rule }}"
      with_fileglob:
        - "config/{{ org }}/log_alert_rules.yml"

    - name: Load cluster-specific alert rules
      tags: always
      ansible.builtin.set_fact:
        axonops_log_alert_rule: "{{ axonops_log_alert_rule + (lookup('file', item) | from_yaml).axonops_log_alert_rule }}"
      with_fileglob:
        - "config/{{ org }}/{{ cluster }}/log_alert_rules.yml"

    - name: Install log alerts on {{ org }}/{{ cluster }}
      axonops.configuration.log_alert_rule:
        org: "{{ org }}"
        cluster: "{{ cluster }}"
        name: "{{ item.name }}"
        content: "{{ item.content |default('') }}"
        operator: "{{ item.operator |default('>=')}}"
        description: "{{ item.description |default('')}}"
        level: "{{ item.level |default('')}}"
        type: "{{ item.type |default('')}}"
        source: "{{ item.source |default('')}}"
        warning_value: "{{ item.warning_value }}"
        critical_value: "{{ item.critical_value }}"
        duration: "{{ item.duration }}"
        present: "{{ item.present|default(true) }}"
      with_items:
        "{{ axonops_log_alert_rule }}"
      tags:
      - axonops_log_alert_rule
      - log_alert_rule
      - alert_rule
      - alert
      - rule

# code: language=ansible
