---
- name: Initialize axonops_log_alert_rule
  tags: always
  ansible.builtin.set_fact:
    axonops_log_alert_rule: []

- name: Load organization-wide alert rules
  tags: always
  ansible.builtin.set_fact:
    axonops_log_alert_rule: "{{ axonops_log_alert_rule + (lookup('file', item) | from_yaml).axonops_log_alert_rule }}"
  with_fileglob:
    - "config/{{ org }}/log_alert_rules.yml"

- name: Load cluster-specific alert rules
  tags: always
  ansible.builtin.set_fact:
    axonops_log_alert_rule: "{{ axonops_log_alert_rule + (lookup('file', item) | from_yaml).axonops_log_alert_rule }}"
  with_fileglob:
    - "config/{{ org }}/{{ cluster }}/log_alert_rules.yml"

- name: "Install log alerts on {{ org }}/{{ cluster }}"
  axonops.configuration.log_alert_rule:
    org: "{{ org }}"
    cluster: "{{ cluster }}"
    cluster_type: "{{ logalert_item.cluster_type | default(omit) }}"
    name: "{{ logalert_item.name }}"
    content: "{{ logalert_item.content | default('') }}"
    operator: "{{ logalert_item.operator | default('>=') }}"
    description: "{{ logalert_item.description | default('') }}"
    level: "{{ logalert_item.level | default('') }}"
    type: "{{ logalert_item.type | default('') }}"
    source: "{{ logalert_item.source | default('') }}"
    warning_value: "{{ logalert_item.warning_value }}"
    critical_value: "{{ logalert_item.critical_value }}"
    duration: "{{ logalert_item.duration }}"
    routing: "{{ logalert_item.routing | default(omit) }}"
    present: "{{ logalert_item.present | default(true) }}"
    dc: "{{ logalert_item.dc | default([]) }}"
    rack: "{{ logalert_item.rack | default([]) }}"
    host_id: "{{ logalert_item.host_id | default([]) }}"
    auth_token: "{{ logalert_item.auth_token | default(omit) }}"
    username: "{{ logalert_item.username | default(omit) }}"
    password: "{{ logalert_item.password | default(omit) }}"

  with_items:
    "{{ axonops_log_alert_rule }}"
  no_log: "{{ false if enable_logging is defined and enable_logging else true }}"
  loop_control:
    loop_var: logalert_item
  tags:
  - axonops_log_alert_rule
  - log_alert_rule
  - alert_rule
  - alert
  - rule

# code: language=ansible
