######## Cassandra Backup Schedules ########
# This is an example set of log alert rules for Cassandra system.log.
# These rules are some examples of how alerts can be configured for
# your Apache Cassandra cluster. The rules defined here will be applied
# only to a specific cluster, and will override the rules defined in
# all/log_alert_rules.yml.
backup:


# Backup Schedules

- name: Schedule a backup to S3 bucket
  remote_type: s3
  cluster: testcluster
  datacenters: dc1
  remote_path: bucketname/path
  local_retention: 10d
  remote_retention: 60d
  tag: "scheduled backup"
  timeout: 10h
  remote: true
  schedule: true
  schedule_expr: 0 1 * * *
  s3_region: eu-west-2
  s3_acl: private

- name: Snapshot a table to an Azure Blob
  remote_type: azure
  cluster: testcluster
  datacenters: dc1
  remote_path: foo
  local_retention: 10d
  remote_retention: 30d
  tag: "Snapshot appTable"
  timeout: 10h
  remote: true
  tables: ['appKeyspace.appTable']
  keyspaces: ['appKeyspace']
  schedule: false
  azure_account: azure_storage_account_name
  azure_use_msi: true
